spring:
  application:
    name: DirectDrop-backend
  jackson:
    time-zone: UTC
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/DirectDrop
      auto-index-creation: true
server:
  port: 8080

logging:
  level:
    root: info

